### ISSUE TITLE
Do Not Use Register.lua as file name, please.

### ISSUE THREAD

**Issue by WilliambWattKin** [loki79uk/FS22_KeyboardSteering#1]
### Concerning Register.lua
Often when working with several script mods and consolidating or intertwining delivery/deployment - many script mods utilize similar 'register.lua'-s...  Could this register.lua be more directly tied to FS22_KeyboardSteering by an additional layer of naming convention?  Such as RegisterKeyboardSteering.lua or KeyboardSteeringRegister.lua?[^note]
[^note]:
    How do I tie this Issue directly to the Register.lua entry in Code?

**Comment by loki79uk** [comment]
I finally got around to changing this for you.  Better late than never.. :D
https://github.com/loki79uk/FS22_KeyboardSteering/commit/d932428bb738f4609a449bc27843292d97f8bee2#diff-f7e533a57104423e3c01868e3becefccb001be84bb7d233d73dca2dbcdcd72c2
